### ISSUE TITLE
Short Rest

### ISSUE THREAD

**Issue by adellanuki** [ZerdBG3/DnD-Rebalancing#103]
Short rest system is not enjoyable at all, it's really intrusive. I understand it's "correct" though, and seeing as I'm not sure where else to ask/comment this but is there a way to disable JUST that part? the rest is fantastic, but playing in Multiplayer with that rest system is not fun. I apologize if this post is in the wrong place.

**Comment by FelipeRenault** [comment]
I really don't see a way to handle Short Rest besides this one, tbh.
I do intend to change some features like Arcane Recovery to actually require the "full stop short rest" status so they can be used, since you theoretically need a Short Rest to use it, it's not a "once per short rest" ability.
With that in mind, it gets even trickier to remove this current system.

I understand the intrusive aspect of it, since it interrupts the gameplay, but, imo, that's how a Short Rest should be. You gotta stop the whole party to get the benefits of a Short Rest. Looking at how Solasta implements it, it's actually more intrusive, since it cuts to a waiting panel and comes back to the game to select hit dice restoration and features (plus item attuning, but that's a whole other issue)
