### ISSUE TITLE
Throwable Weapons

### ISSUE THREAD

**Issue by FelipeRenault** [ZerdBG3/DnD-Rebalancing#107]
- The attack roll for any throwable object is now `data "SpellRoll" "Attack(AttackType.MeleeUnarmedAttack)"`, meaning any weapon thrown won't apply its properties when thrown, such as bonus to attack rolls or even the finesse property to use dexterity instead of strength on the attack roll (damage roll is fine)

**Comment by beargorr** [comment]
Sorry if I am misreading, but shouldn't thrown weapons still maintain finesse in RAW? 

"If the weapon is a melee weapon, you use the same ability modifier for that Attack roll and damage roll that you would use for a melee Attack with the weapon. For example, if you throw a Handaxe, you use your Strength, but if you throw a Dagger, you can use either your Strength or your Dexterity, since the Dagger has the finesse property."

https://roll20.net/compendium/dnd5e/Weapons#content

**Comment by FelipeRenault** [comment]
Yes, that's exactly the problem
