### ISSUE TITLE
Fix Rogue sneak attack

### ISSUE THREAD

**Issue by AshnakAGQ** [ZerdBG3/DnD-Rebalancing#18]
Rogue sneak attack is supposed to increase to 2d6 at level 3. It currently stays at 1d6. It's supposed to be more powerful than Hex or Hunter's mark seeing as it can only apply once per turn.

**Comment by FelipeRenault** [comment]
The spell calculation is as follows
```
DealDamage(1d6*(((Level-1)/2)+1), MainMeleeWeaponDamageType)
```
Are you sure the damage is not increasing? Please test it and check the combat log roll, the tooltip might be broken, even if it's working correctly
Here's the (possibly wrong) spell's description params
```
data "DescriptionParams" "DealDamage(MainMeleeWeapon+1d6, MainMeleeWeaponDamageType)"
```

**Comment by AshnakAGQ** [comment]
Just checked the damage roll and it does seem to be scaling properly. The description is just wrong, and the level up doesn't mention anything either.

**Comment by Slapstick83** [comment]
The problem here is that it rolls 1d6 and then multiplies it, when it should roll 1d6 per 2 levels. The difference in rolling 1d6*x and xd6 is pretty huge when we get to higher level. It massively impacts the damage distribution. With 5d6 you'd have a bell curve with a high likelyhood of moderate damage, with 1d6 x 5 you'll have equal chance of very low damage and very high damage. The big  draw of sneak attack is reliable damage.

**Comment by FelipeRenault** [comment]
Agreed, but that's something Larian should fix before release. Since for now we only get up to 2d6 vs 1d6*2, I won't bother
