### ISSUE TITLE
Two Weapon Fighting - 2nd phase

### ISSUE THREAD

**Issue by Dapoulp** [ZerdBG3/DnD-Rebalancing#48]
Hi !
Ty for the dual wield fixes.

There are 2 things that still need to be fixed about Offhand damage:
1. You substract DexterityModifier on Finesse weapon but if your Strength is better then your Dexterity, the used modifier is the Strength one. So the "SpellSuccess" entry for "Target_OffhandAttack" should be: `IF(WieldingFinesseWeapon(context.Source)):DealDamage(max(1,OffhandMeleeWeapon)-max(0, max(StrengthModifier, DexterityModifier)), OffhandMeleeWeaponDamageType); ....`
2. Two-Weapon Fighting style should add Strength/Dexterity modifier to off-hand damage. I'm working on it (maybe using a tag when you get the fighting style), I'll let you know when I get a working fix.

**Comment by Dapoulp** [comment]
Ok, I managed to make it work with right Ability modifier and Two-Weaon Fighting Style. No need for custom tag as there is already a function to check if the character got a specific passive.
So, in "Spell_Target_Zerd.tvt", just replace the "SpellSuccess" content of "Target_OffhandAttack" with:
`IF(WieldingFinesseWeapon(context.Source) and not(HasPassive('FightingStyle_TwoWeaponFighting',context.Source))):DealDamage(max(1,OffhandMeleeWeapon)-max(0,max(StrengthModifier,DexterityModifier)), OffhandMeleeWeaponDamageType);IF(WieldingFinesseWeapon(context.Source) and HasPassive('FightingStyle_TwoWeaponFighting',context.Source)):DealDamage(max(1,OffhandMeleeWeapon), OffhandMeleeWeaponDamageType);IF(not WieldingFinesseWeapon(context.Source) and not(HasPassive('FightingStyle_TwoWeaponFighting',context.Source))):DealDamage(max(1,OffhandMeleeWeapon)-max(0,StrengthModifier), OffhandMeleeWeaponDamageType);IF(not WieldingFinesseWeapon(context.Source) and HasPassive('FightingStyle_TwoWeaponFighting',context.Source)):DealDamage(max(1,OffhandMeleeWeapon), OffhandMeleeWeaponDamageType);ExecuteWeaponFunctors(OffHand)`

**Comment by FelipeRenault** [comment]
Thanks for the suggestions! Feel free to open a PR next time. Here's the end result
`data "SpellSuccess" "IF(HasPassive('FightingStyle_TwoWeaponFighting')):DealDamage(max(1,OffhandMeleeWeapon),OffhandMeleeWeaponDamageType);IF(not HasPassive('FightingStyle_TwoWeaponFighting') and WieldingWeapon('Finesse', true, false, context.Source)):DealDamage(max(1,OffhandMeleeWeapon)-max(0,max(StrengthModifier,DexterityModifier)),OffhandMeleeWeaponDamageType);IF(not HasPassive('FightingStyle_TwoWeaponFighting') and not WieldingWeapon('Finesse', true, false, context.Source)):DealDamage(max(1,OffhandMeleeWeapon)-max(0,StrengthModifier), OffhandMeleeWeaponDamageType);ExecuteWeaponFunctors(OffHand);"`
Only one condition is needed if the target has the Two Weapon Fighting Style, since I don't need to subtract the modifier anyways (using the bug at our favor here). Also, I changed `WieldingFinesseWeapon` for a more specific check using `WieldingWeapon('Finesse', true, false, context.Source)`. This checks if the offhand weapon is Finesse, not considering the main hand at all (the second parameter is `false` for mainhand and `true` for offhand)
