### ISSUE TITLE
[Rogue] Thief

### ISSUE THREAD

**Issue by FelipeRenault** [ZerdBG3/DnD-Rebalancing#78]
Remove the extra ~bonus~ bonus action
Possible replacements:
- [X] Second-Story Work: make jumping scale with dexterity
- [X] Fast Hands: Add Help as a bonus action

**Comment by FelipeRenault** [comment]
It seems the Throw action is beyond hardcoded, so I couldn't make a bonus action replacement for it, unfortunately.
I'm looking for suggestions on what to add to Thief

**Comment by DubhHerder** [comment]
Possibly add a thief only bonus action version of the help option. I.e.  `Target_Help_Thief` in the  `Spell_Target` file would include: 

`data "UseCosts" "BonusActionPoint:1"` 
instead of 
`data "UseCosts" "ActionPoint:1`.

The `Target_Help` action currently only removes negative status effects and does not grant advantage to others so it is mechanically similar to the use of an object bonus action that Fast Hands allows (bonus action of applying healing potions to others, pulling a knife to cut free a restrained person, etc) .

**Comment by FelipeRenault** [comment]
That might be a good idea. I'm a little uncomfortable because Help is used to instantly heal 1 HP from a Downed character and bring them back to the fight, so I might make a Help that doesn't do just that, but do the rest as a bonus action

**Comment by DubhHerder** [comment]
Seems reasonable. The current Help option has effectively a free Healer feat incorporated in it. It seems to be a standard approach for Larian to add feats here and there to make things more appealing (Mage hand is the Telekinetic feat etc). 

Would changing `IF(HasStatus('DOWNED')):RegainHitPoints(1)` to `IF(HasStatus('DOWNED')):Stabilize()` be reasonable? 

Mechanically it would change Help from being a free Healer Feat to a single use of a Healer's Kit. This stays in line with Fast Hands "use an object" bonus action and the Healer's Kit feature seems unlikely to be added otherwise.

**Comment by FelipeRenault** [comment]
Is `Stabilize()` an actual thing in BG3? I've been looking into ways of removing the free healing from Help for quite a while and couldn't reliable make a character stabilized without requiring a new status or having them roll 3 successes on Downed

**Comment by DubhHerder** [comment]
It's under Spare_The_Dying in the shared Spell_Target.txt.

the cantrip doesn't seem to be fully implemented as it's not available to choose in game yet but I was able to add it manually. 

Other than a missing icon, it looked ok in the hotbar. I only found it today so I haven't tested it on a downed character to see if it's fully functional yet.

I've also seen reference to regainhitpoints(0) in other sections but again I haven't had a chance to check if it's similar or not to stabilise()

**Comment by FelipeRenault** [comment]
Thanks for the info, it'll be useful for #5 as well
I'll be testing it out later

**Comment by FelipeRenault** [comment]
@DubhHerder it does work. And I managed to require a Medicine check, and also managed to script a little hack alongside it so you get a instant healing from being stabilized when leaving combat or if you're stabilized out of combat. Thanks a bunch!
Now, I'll also make a Help action focused on distracting targets and granting advantage, plus I'll provide the original Help as bonus actions to Thieves
