### ISSUE TITLE
[Spell] Prestidigitation or elemental cantrips for surface effect management/clean up

### ISSUE THREAD

**Issue by DubhHerder** [ZerdBG3/DnD-Rebalancing#81]
I've see some people having issues with surface effects lasting forever, poor AI pathing, and the party chaining system combining to TPK out of combat.  There are a few 5E cantrips that would allow the clean up of such surface effects. The cantrips have multiple effects but i am focusing on surface effect cleaning only for this issue.

A general single cantrip solution:

- Prestidigitation can snuff small campfires and clean a volume of 1 cubic ft (12 sqft area if 1 inch deep). In game it could target and remove small areas of fire/poison/blood/acid/mud/alcohol/oil/grease/webs/ash/powder by RAW. 

or a 4 cantrip solution:

- Shape Water can freeze water/melt ice and move water/clouds  
- Mold Earth can create or remove difficult terrain
- Control Flames to extinguish fires
- Gust can move a 5lb object with a single action but can not remove clouds by RAW. Out of combat if a cloud persists then i think it would be RAI to allow Gust to disperse a cloud over a few rounds

It might be excessive to add in the 4 elemental cantrips now (especially if Larian will be adding them later). An intermediate general solution could be a slightly buffed version of Prestidigitation that also allows removal of water and cloud surface effects out of combat. This would be a generous reading of the spell effects but not completely unfounded as Prestidigitation can warm things and create a puff of air by RAW so evaporating water and moving clouds should be possible over time. 

The spell `Target_DestroyWater` in `Stats\Generated\Data\Spell_Target` file could be used as a template with alterations to spell level, range and area as it already removes many surface effects at the cost of a spellslot. The cost of a spellslot to clean surfaces seems reasonable in combat but seems excessive for non-RAW surface effects out of combat.  The `TargetRadius` would be changed from 9 to 3 and the `AreaRadius` would be changed from 4 to 1 (rounded up to whole number) because `AreaRadius` requires a `ConstantInt`.

If you are concerned about mechanical balance in combat, limiting these cantrips to out of combat usage via `data "Requirements" "!Combat"` tag could allow a quality of life improvement without affecting combat.

What are your thoughts on this?  Which approach would be more appropriate, a single slightly buffed prestidigitation or all 5 cantrips? Do you think this is useful or unnecessary? If unnecessary then please close issue and thanks for reading. 

I haven't contributed to github project before and was unsure on etiquette about which should be done first: forking or raising issues. Would you prefer to work on it yourself or review my possibly bugged code ? (because of my lack of experience with github and how the various files of Larian's engine interconnect).

**Comment by FelipeRenault** [comment]
Thanks for contributing to the project. Regarding etiquette, don't worry: I haven't set up a guide, so feel free to open issues and even submit pull requests if you wish. If you actually code it, I'll review the code and even test it out myself before accepting, so don't feel disencouraged to try it out.
If you wish, you can also hop on my Discord server and we can do a little pair programming so I can take a look even before you create the pull request, and maybe teach you a bit about GitHub.

Regarding the actual issue, currently I'm trying to avoid adding content from the PHB, because I do believe a lot of them will be added by Larian in some form eventually, so I don't want to waste my work by doing something that will be done in the future. I'm focusing more on altering already existing content that I don't think Larian will fix themselves. However, I'm not against adding content, I just don't want to work on it. If you wish to add a cantrip, or 5, feel free to do it and I'll incorporate into the mod, as long as it follows the PHB (with some small space for creativity, as the changes to Prestidigitation mentioned)

**Comment by DubhHerder** [comment]
After thinking about it, I agree that your approach of improving on existing content is a better focus than adding content for this project. 

I put together a [working version of Prestidigitation for surface effects](https://github.com/DubhHerder/Prestidigitation_BG3) but am no longer as sure it should be added here as I was before.  I think I would like to do more testing and fix a few issues before I might submit it.   

Maybe this issue should be closed for now and revisited in the future.

**Comment by FelipeRenault** [comment]
Alright, no worries
I looked into the project you linked and created a [pull request](https://github.com/DubhHerder/Prestidigitation_BG3/pull/1) with a few suggestions
I'll close this issue for now, and people interested in having a functioning prestidigitation can look into [your mod](https://github.com/DubhHerder/Prestidigitation_BG3) instead
